FROM gcr.io/deeplearning-platform-release/pytorch-cpu:latest

WORKDIR /app

RUN curl -f https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | apt-key add -

RUN apt-get update
RUN apt-get install git libgl1-mesa-glx ffmpeg libsm6 libxext6 -y

RUN conda init bash
RUN conda create -n gate python=3.10 -y
RUN echo "conda activate gate" >> ~/.bashrc
ENV PATH /opt/conda/envs/gate/bin:$PATH

RUN /bin/bash -c "source activate gate \
    && conda install nvidia-ml pytorch torchvision torchaudio cpuonly -c pytorch -c conda-forge"

COPY ./requirements.txt ./requirements.txt

RUN /bin/bash -c "source activate gate \
    && pip install -r requirements.txt"

RUN /bin/bash -c "source activate gate \ 
    && pip install git+https://github.com/openai/CLIP.git@main"

RUN /bin/bash -c "source activate gate \ 
    &&  pip install git+https://github.com/AntreasAntoniou/TALI.git@main"

COPY ./ /app/

RUN /bin/bash -c "source activate gate \ 
    && pip install ."

ENTRYPOINT [ "/bin/bash" ]